version: "3.3"

services:
  db:
    container_name: drogaraia_db
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DrogaRaia

  nginx:
    container_name: drogaraia_nginx
    build: docker_images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8080:80"
    depends_on:
      - db
      - php

  php:
    container_name: drogaraia_php
    build: docker_images/php
    volumes:
      - ./lumen:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
    ports:
      - "9000:9000"
    depends_on:
      - db